#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE6DFB08CE8B11277 (fcosta@trustwave.com)
#
Name     : modsecurity
Version  : 3.0.4
Release  : 1
URL      : https://github.com/SpiderLabs/ModSecurity/releases/download/v3.0.4/modsecurity-v3.0.4.tar.gz
Source0  : https://github.com/SpiderLabs/ModSecurity/releases/download/v3.0.4/modsecurity-v3.0.4.tar.gz
Source1  : https://github.com/SpiderLabs/ModSecurity/releases/download/v3.0.4/modsecurity-v3.0.4.tar.gz.asc
Summary  : ModSecurity API
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: modsecurity-bin = %{version}-%{release}
Requires: modsecurity-lib = %{version}-%{release}
Requires: modsecurity-license = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : nghttp2-dev
BuildRequires : openssl-dev
BuildRequires : perl
BuildRequires : pkgconfig(libpcre)
BuildRequires : valgrind

%description
<img src="https://github.com/SpiderLabs/ModSecurity/raw/v3/master/others/modsec.png" width="50%">

%package bin
Summary: bin components for the modsecurity package.
Group: Binaries
Requires: modsecurity-license = %{version}-%{release}

%description bin
bin components for the modsecurity package.


%package dev
Summary: dev components for the modsecurity package.
Group: Development
Requires: modsecurity-lib = %{version}-%{release}
Requires: modsecurity-bin = %{version}-%{release}
Provides: modsecurity-devel = %{version}-%{release}
Requires: modsecurity = %{version}-%{release}

%description dev
dev components for the modsecurity package.


%package lib
Summary: lib components for the modsecurity package.
Group: Libraries
Requires: modsecurity-license = %{version}-%{release}

%description lib
lib components for the modsecurity package.


%package license
Summary: license components for the modsecurity package.
Group: Default

%description license
license components for the modsecurity package.


%prep
%setup -q -n modsecurity-v3.0.4
cd %{_builddir}/modsecurity-v3.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587592155
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --disable-examples
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1587592155
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/modsecurity
cp %{_builddir}/modsecurity-v3.0.4/LICENSE %{buildroot}/usr/share/package-licenses/modsecurity/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/modsecurity-v3.0.4/others/libinjection/COPYING %{buildroot}/usr/share/package-licenses/modsecurity/2f52f7e673436d231eb560ccfc057715bc069c67
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/modsec-rules-check

%files dev
%defattr(-,root,root,-)
/usr/include/modsecurity/actions/action.h
/usr/include/modsecurity/anchored_set_variable.h
/usr/include/modsecurity/anchored_variable.h
/usr/include/modsecurity/audit_log.h
/usr/include/modsecurity/collection/collection.h
/usr/include/modsecurity/collection/collections.h
/usr/include/modsecurity/debug_log.h
/usr/include/modsecurity/intervention.h
/usr/include/modsecurity/modsecurity.h
/usr/include/modsecurity/rule.h
/usr/include/modsecurity/rule_message.h
/usr/include/modsecurity/rules.h
/usr/include/modsecurity/rules_exceptions.h
/usr/include/modsecurity/rules_properties.h
/usr/include/modsecurity/transaction.h
/usr/include/modsecurity/variable_origin.h
/usr/include/modsecurity/variable_value.h
/usr/lib64/libmodsecurity.so
/usr/lib64/pkgconfig/modsecurity.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmodsecurity.so.3
/usr/lib64/libmodsecurity.so.3.0.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/modsecurity/2f52f7e673436d231eb560ccfc057715bc069c67
/usr/share/package-licenses/modsecurity/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
